### ISSUE TITLE
Bug when PBC and Atoms are outside the cell

### ISSUE THREAD

**Issue by cortner** [libAtoms/NeighbourLists.jl#6]
at the moment _fix_cell_ provides a workaround, but doesn't fix the bug. See [JuLIP.jl:#99](https://github.com/libAtoms/JuLIP.jl/issues/99) an example to reproduce this.

**Comment by jameskermode** [comment]
Just ran into this again with some non-periodic cells where cell was set to the zero matrix. `_fix_cell_()` doesn't seem to cope with this case. For now I fixed by hand but will see if I can come up with a general solution.

**Comment by cortner** [comment]
I wonder whether there is scope to just ignore the cell argument entirely and compute it an the fly if PBC is not used.

**Comment by cortner** [comment]
The bug is still present in the v0.6 `SortedCellList` + `for_each_neighbour` path. Below is a self-contained minimal reproducer (just NL.jl + StaticArrays, no other deps) that doesn't go through the legacy `PairList`.

```julia
using NeighbourLists, StaticArrays, LinearAlgebra

# Two atoms 1.0 Å apart along y, in a periodic 8×8×8 box, cutoff 1.5.
cell = SMatrix{3,3,Float64}(8.0 * I)
pbc  = SVector{3,Bool}(true, true, true)

function report(X)
    clist = neighbour_list(X, 1.5, cell, pbc; lazy = true)
    for i in 1:length(X)
        found = []
        for_each_neighbour(clist, i) do j, R, S
            push!(found, (j, sqrt(sum(abs2, R))))
        end
        println(\"  atom \$i neighbours: \", found)
    end
end

println(\"Case A — both atoms in [0, L) (y = 0.5, y = 1.5):\")
report([SVector(0.5, 0.5, 0.5), SVector(0.5, 1.5, 0.5)])

println(\"\nCase B — atom 2 just outside [0, L) (y = -0.5):\")
report([SVector(0.5, 0.5, 0.5), SVector(0.5, -0.5, 0.5)])

println(\"\nCase C — atom 2 fully outside one period (y = -7.5, wraps to y = 0.5):\")
report([SVector(0.5, 0.5, 0.5), SVector(0.5, -7.5, 0.5)])
```

Output:
```
Case A — both atoms in [0, L) (y = 0.5, y = 1.5):
  atom 1 neighbours: Any[(2, 1.0)]
  atom 2 neighbours: Any[(1, 1.0)]

Case B — atom 2 just outside [0, L) (y = -0.5):
  atom 1 neighbours: Any[]
  atom 2 neighbours: Any[]

Case C — atom 2 fully outside one period (y = -7.5, wraps to y = 0.5):
  atom 1 neighbours: Any[]
  atom 2 neighbours: Any[]
```

The periodic-image distance is `1.0` Å in all three cases (≪ cutoff = `1.5`). Cases B and C should match Case A; they instead return empty neighbour lists.

### Where this comes up in practice

In [ACEsuit/MultilevelSummation.jl](https://github.com/ACEsuit/MultilevelSummation.jl)'s short-range pair sum, on a `Tune.build_h2o(8.0)` fixture (TIP3P water, 17 molecules, Poisson-disk packing), `for_each_neighbour` returns **66 of 74 ordered pairs**. The missed pairs are intramolecular OH bonds where the H atom landed slightly outside `[0, L)` along one axis after random molecular rotation. Net effect: ~1 % U_short error and up to ~50 % per-atom force error.

### Looks like the same root cause as the 2021 report

`SortedCellList` bins atoms by mapping their coordinates into `[0, L)` for the cell index, but stores the unwrapped positions. The iteration over adjacent cells then computes the pair vector from the unwrapped positions plus the cell-shift increment, which doesn't recover the correct minimum-image geometry when the source atom started outside `[0, L)`.

### Possible fix

Wrap positions into `[0, L)` along each periodic axis inside `_build_sorted_celllist` before storing them in `X` / `X_orig`. The unwrapped form can still be kept around in a separate field if needed for diagnostics, but the values that the iteration arithmetic relies on must be the wrapped ones. Then the existing cell-shift arithmetic gives the correct minimum-image vector.

(Tracking on the downstream side as ACEsuit/MultilevelSummation.jl#9.)
